Vagrant.configure("2") do |config|

    config.vm.define "ubuntu" do |ubuntu_config|
      ubuntu_config.vm.box = "bento/ubuntu-20.04"
      ubuntu_config.vm.network "private_network", ip: "192.168.50.10"
      ubuntu_config.vm.network "forwarded_port", guest: 5000, host: 5000
      ubuntu_config.vm.synced_folder ".", "/home/vagrant/crossplat"
  
      ubuntu_config.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu"
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = 4
      end
  
      ubuntu_config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -y
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-8.0

        sudo apt install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker pull loicsharma/baget
        sudo docker run -d -p 5000:80 --name baget loicsharma/baget
        export PATH="$PATH:/home/vagrant/.dotnet/tools"
        dotnet nuget add source "http://192.168.50.11:5000/v3/index.json" -n "repos"
        dotnet tool install --global aadzhiiev --version 1.0.0 --add-source http://192.168.50.4:5000/v3/index.json
      SHELL
    end
  

    config.vm.define "windows" do |windows_config|
        windows_config.vm.box = "microsoft/windows-10"
      windows_config.vm.network "private_network", ip: "192.168.50.12"
      windows_config.vm.network "forwarded_port", guest: 5000, host: 5000
      windows_config.vm.synced_folder ".", "C:/crossplat"
  
      windows_config.vm.provider "virtualbox" do |vb|
        vb.name = "windows"
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = 2
      end
  
      windows_config.vm.provision "powershell", inline: <<-SHELL
        Invoke-WebRequest -Uri https://aka.ms/install-dotnet.ps1 -OutFile dotnet-install.ps1
        choco install docker-desktop -y
        & "C:/Program Files/Docker/Docker/Docker Desktop.exe" &
        docker pull loicsharma/baget
        docker run -d -p 5000:80 --name baget loicsharma/baget
        dotnet nuget add source "http://192.168.50.5:5000/v3/index.json" -n "repo"
        dotnet tool install --global aadzhiiev --version 1.0.0 --add-source http://192.168.50.5:5000/v3/index.json
      SHELL
    end

  
  end
  